# Reference: http://code.google.com/intl/fr-FR/appengine/docs/python/config/appconfig.html
application: catholiquefr
version: 0-4-6
runtime: python
api_version: 1

handlers:
- url: /
  script: recherche/recherche.py
- url: /api/navigation_bar.0-4.js
  script: navigation_bar/0-4/navigation_bar.py
- url: /stylesheets
  static_dir: stylesheets
- url: /img
  static_dir: img
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
