# Reference: http://code.google.com/intl/fr-FR/appengine/docs/python/config/appconfig.html
application: catholiquefr
version: 1-0-6
runtime: python
api_version: 1

handlers:
- url: /
  script: recherche/recherche.py
  
- url: /api/navigation_bar.0-4.js
  script: navigation_bar/0-4/navigation_bar.py
  
- url: /api/.*
  script: navigation_bar/1-0/navigation_bar.py

- url: /admin/import
  script: admin/import/import.py

- url: /admin/menus/.*
  script: admin/admin.py

- url: /admin/navbars/.*
  script: admin/navbar.py

- url: /admin/.*
  script: admin/admin.py
  login: admin
  
- url: /dioceses/.*
  script: dioceses/dioceses.py
  login: required

- url: /gdata
  script: gdata_test.py

- url: /stylesheets
  static_dir: stylesheets
  
- url: /javascripts
  static_dir: javascripts
  
- url: /img
  static_dir: img
  
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /tests
  static_dir: tests